<a href="https://colab.research.google.com/github/Eric428-a/DataPreprocessingProject/blob/main/Data_Preprocssing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORTING LIBRARIES

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt


# IMPORTING THE DATASET

In [ ]:
dataset = pd.read_csv("Book.csv")

In [ ]:
dataset

State   Age  Salary Purchased
0  California  42.0    60.0        No
1     Florida  29.0    55.0       Yes
2       Texas  27.0    72.0        No
3     Florida  26.0    48.0        No
4       Texas  39.0     NaN       Yes
5  California  34.0    54.0       Yes
6     Florida   NaN    57.0        No
7  California  46.0    80.0       Yes
8       Texas  51.0    85.0        No
9  California  38.0    75.0       Yes

In [ ]:
dataset.head

<bound method NDFrame.head of         State   Age  Salary Purchased
0  California  42.0    60.0        No
1     Florida  29.0    55.0       Yes
2       Texas  27.0    72.0        No
3     Florida  26.0    48.0        No
4       Texas  39.0     NaN       Yes
5  California  34.0    54.0       Yes
6     Florida   NaN    57.0        No
7  California  46.0    80.0       Yes
8       Texas  51.0    85.0        No
9  California  38.0    75.0       Yes>

In [ ]:
dataset.columns

Index(['State', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
dataset.count()

State        10
Age           9
Salary        9
Purchased    10
dtype: int64

In [ ]:
dataset.describe()

Age     Salary
count   9.000000   9.000000
mean   36.888889  65.111111
std     8.666667  13.100042
min    26.000000  48.000000
25%    29.000000  55.000000
50%    38.000000  60.000000
75%    42.000000  75.000000
max    51.000000  85.000000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   State      10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
x = dataset.iloc[ :, 0 : 3].values

In [ ]:
type(x)

numpy.ndarray

In [ ]:
print(x)

[['California' 42.0 60.0]
 ['Florida' 29.0 55.0]
 ['Texas' 27.0 72.0]
 ['Florida' 26.0 48.0]
 ['Texas' 39.0 nan]
 ['California' 34.0 54.0]
 ['Florida' nan 57.0]
 ['California' 46.0 80.0]
 ['Texas' 51.0 85.0]
 ['California' 38.0 75.0]]


In [ ]:
y = dataset.iloc[ : , -1].values

In [ ]:
type(y)

numpy.ndarray

In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# WORKING WITH MISSING DATA

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values= np.nan, strategy="mean")

In [ ]:
x


array([['California', 42.0, 60.0],
       ['Florida', 29.0, 55.0],
       ['Texas', 27.0, 72.0],
       ['Florida', 26.0, 48.0],
       ['Texas', 39.0, nan],
       ['California', 34.0, 54.0],
       ['Florida', nan, 57.0],
       ['California', 46.0, 80.0],
       ['Texas', 51.0, 85.0],
       ['California', 38.0, 75.0]], dtype=object)

In [ ]:
x[ :, 1:3]

array([[42.0, 60.0],
       [29.0, 55.0],
       [27.0, 72.0],
       [26.0, 48.0],
       [39.0, nan],
       [34.0, 54.0],
       [nan, 57.0],
       [46.0, 80.0],
       [51.0, 85.0],
       [38.0, 75.0]], dtype=object)

In [ ]:
imputer.fit(x[ :, 1:3])

SimpleImputer()

In [ ]:
x

array([['California', 42.0, 60.0],
       ['Florida', 29.0, 55.0],
       ['Texas', 27.0, 72.0],
       ['Florida', 26.0, 48.0],
       ['Texas', 39.0, nan],
       ['California', 34.0, 54.0],
       ['Florida', nan, 57.0],
       ['California', 46.0, 80.0],
       ['Texas', 51.0, 85.0],
       ['California', 38.0, 75.0]], dtype=object)

In [ ]:
imputer.transform(x[ :, 1:3] )

array([[42.        , 60.        ],
       [29.        , 55.        ],
       [27.        , 72.        ],
       [26.        , 48.        ],
       [39.        , 65.11111111],
       [34.        , 54.        ],
       [36.88888889, 57.        ],
       [46.        , 80.        ],
       [51.        , 85.        ],
       [38.        , 75.        ]])

In [ ]:
x[ :, 1:3] = imputer.transform(x[ :, 1:3] )

In [ ]:
print(x)


[['California' 42.0 60.0]
 ['Florida' 29.0 55.0]
 ['Texas' 27.0 72.0]
 ['Florida' 26.0 48.0]
 ['Texas' 39.0 65.11111111111111]
 ['California' 34.0 54.0]
 ['Florida' 36.888888888888886 57.0]
 ['California' 46.0 80.0]
 ['Texas' 51.0 85.0]
 ['California' 38.0 75.0]]


# ENCODING CATEGORICAL DATA

In [ ]:
from sklearn.compose import ColumnTransformer


In [ ]:
from sklearn.preprocessing import OneHotEncoder


In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder = 'passthrough')


In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 42.0 60.0]
 [0.0 1.0 0.0 29.0 55.0]
 [0.0 0.0 1.0 27.0 72.0]
 [0.0 1.0 0.0 26.0 48.0]
 [0.0 0.0 1.0 39.0 65.11111111111111]
 [1.0 0.0 0.0 34.0 54.0]
 [0.0 1.0 0.0 36.888888888888886 57.0]
 [1.0 0.0 0.0 46.0 80.0]
 [0.0 0.0 1.0 51.0 85.0]
 [1.0 0.0 0.0 38.0 75.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
le = LabelEncoder()

In [ ]:
y = le.fit_transform(y)


In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# SPLITTING DATASET INTO TRAIN AND TEST

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
x_train

array([[0.0, 0.0, 1.0, 39.0, 65.11111111111111],
       [1.0, 0.0, 0.0, 38.0, 75.0],
       [0.0, 1.0, 0.0, 29.0, 55.0],
       [0.0, 1.0, 0.0, 36.888888888888886, 57.0],
       [1.0, 0.0, 0.0, 46.0, 80.0],
       [0.0, 1.0, 0.0, 26.0, 48.0],
       [1.0, 0.0, 0.0, 42.0, 60.0],
       [1.0, 0.0, 0.0, 34.0, 54.0]], dtype=object)

In [ ]:
x_test

array([[0.0, 0.0, 1.0, 27.0, 72.0],
       [0.0, 0.0, 1.0, 51.0, 85.0]], dtype=object)

In [ ]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [ ]:
y_test

array([0, 0])

# FEATURE SCALING

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()


In [ ]:
x_train[:, 1:] = sc.fit_transform(x_train[:, 1:])

In [ ]:
x_test[:, 1:] = sc.transform(x_test[:, 1:])

In [ ]:
print(x_train)

[[0.0 -0.7745966692414834 2.6457513110645903 0.429679545229809
  0.3266101417092245]
 [1.0 -0.7745966692414834 -0.3779644730092272 0.26685361230061805
  1.2915330499953959]
 [0.0 1.2909944487358056 -0.3779644730092272 -1.1985797840621009
  -0.6599964274373109]
 [0.0 1.2909944487358056 -0.3779644730092272 0.08593590904596088
  -0.4648434796940403]
 [1.0 -0.7745966692414834 -0.3779644730092272 1.5694610757341458
  1.7794154193535725]
 [0.0 1.2909944487358056 -0.3779644730092272 -1.6870575828496737
  -1.3430317445387583]
 [1.0 -0.7745966692414834 -0.3779644730092272 0.9181573440173819
  -0.17211405807913424]
 [1.0 -0.7745966692414834 -0.3779644730092272 -0.3844501194161459
  -0.7575729013089463]]


In [ ]:
print(x_test)

[[0.0 -0.7745966692414834 2.6457513110645903 -1.5242316499204827
  0.9988036283804899]
 [0.0 -0.7745966692414834 2.6457513110645903 2.3835907403801007
  2.2672977887117494]]
